### ISSUE TITLE
java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by kalessil** [Haehnchen/idea-php-drupal-symfony2-bridge#37]
de.espend.idea.php.drupal.index.ConfigEntityTypeAnnotationIndex.lambda$getIndexer$0 (line 47): tried to access method fr.adrienbrault.idea.symfony2plugin.stubs.indexes.RoutesStubIndex.isValidForIndex(Lcom/intellij/util/indexing/FileContent;Lcom/intellij/psi/PsiFile;)Z from class de.espend.idea.php.drupal.index.ConfigEntityTypeAnnotationIndex

No complete stack trace, unfortunately: only this info is available.

**Comment by SpadXIII** [comment]
I keep getting the same errors right after updating to latest PhpStorm (2017.2.4)
Reinstalling the plugin did not help.

Details tab of the message:
```Error while indexing /opt/PhpStorm-2017.2.1/plugins/php/lib/php.jar!/stubs/xdebug/xdebug.php
To reindex this file IDEA has to be restarted: tried to access method fr.adrienbrault.idea.symfony2plugin.stubs.indexes.RoutesStubIndex.isValidForIndex(Lcom/intellij/util/indexing/FileContent;Lcom/intellij/psi/PsiFile;)Z from class de.espend.idea.php.drupal.index.ConfigEntityTypeAnnotationIndex
java.lang.IllegalAccessError: tried to access method fr.adrienbrault.idea.symfony2plugin.stubs.indexes.RoutesStubIndex.isValidForIndex(Lcom/intellij/util/indexing/FileContent;Lcom/intellij/psi/PsiFile;)Z from class de.espend.idea.php.drupal.index.ConfigEntityTypeAnnotationIndex
	at de.espend.idea.php.drupal.index.ConfigEntityTypeAnnotationIndex.lambda$getIndexer$0(ConfigEntityTypeAnnotationIndex.java:47)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1615)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1551)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1510)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:342)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
(this is repeated several times)

**Comment by Haehnchen** [comment]
thx for reporting, thats because of the Symfony Plugin update. I dropped several APIs, but i missed one usage here. Will update this plugin later this day

**Comment by kalessil** [comment]
Thanks!

**Comment by Haehnchen** [comment]
done with 5.0
